from rupy import Rupy
from rupy.pythonize import compile_to
dexp = Rupy.DModule(
  modname="main",
  exports=[],
  stmts=[
    Rupy.DModule(
      modname="Main",
      exports=[
        (
          "cons",
          "cons._3",
        ),
        (
          "main",
          "main._4",
        ),
        (
          "println",
          "println._2",
        ),
      ],
      stmts=[
        Rupy.DLoc(
          lineno=3,
          colno=1,
          val=Rupy.DImport(
            paths=[
              "rupy",
            ],
            name="api",
            actual="api._0",
          ),
        ),
        Rupy.DLoc(
          lineno=5,
          colno=1,
          val=Rupy.DImport(
            paths=[
              "rupy",
            ],
            name="rt",
            actual="rt._1",
          ),
        ),
        Rupy.DLoc(
          lineno=7,
          colno=1,
          val=Rupy.DAssign(
            reg="println._2",
            val=Rupy.DAttr(
              subject=Rupy.DVar(
                sym="api._0",
              ),
              attr="println",
            ),
          ),
        ),
        Rupy.DConst(v=None),
        Rupy.DLoc(
          lineno=10,
          colno=1,
          val=Rupy.DAssign(
            reg="cons._3",
            val=Rupy.DAttr(
              subject=Rupy.DVar(
                sym="rt._1",
              ),
              attr="LinkedList",
            ),
          ),
        ),
        Rupy.DLoc(
          lineno=12,
          colno=1,
          val=Rupy.DAssign(
            reg="main._4",
            val=Rupy.DLoc(
              lineno=12,
              colno=12,
              val=Rupy.DClosure(
                freevars=[
                  "cons._3",
                  "println._2",
                ],
                argnames=[
                  "_._5",
                ],
                body=Rupy.DLoc(
                  lineno=13,
                  colno=5,
                  val=Rupy.DBlock(
                    elts=[
                      Rupy.DAssign(
                        reg="l._6",
                        val=Rupy.DLoc(
                          lineno=13,
                          colno=16,
                          val=Rupy.DCall(
                            f=Rupy.DVar(
                              sym="cons._3",
                            ),
                            args=[
                              Rupy.DConst(v=1),
                              Rupy.DLoc(
                                lineno=13,
                                colno=27,
                                val=Rupy.DCall(
                                  f=Rupy.DVar(
                                    sym="cons._3",
                                  ),
                                  args=[
                                    Rupy.DLoc(
                                      lineno=13,
                                      colno=22,
                                      val=Rupy.DConst(v="\"2\""),
                                    ),
                                    Rupy.DLoc(
                                      lineno=13,
                                      colno=33,
                                      val=Rupy.DList(
                                        elts=[
                                          Rupy.DConst(v=3),
                                          Rupy.DConst(v=4),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Rupy.DCall(
                        f=Rupy.DVar(
                          sym="println._2",
                        ),
                        args=[
                          Rupy.DVar(
                            sym="l._6",
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
              ),
            ),
          ),
        ),
        Rupy.DLoc(
          lineno=16,
          colno=1,
          val=Rupy.DBlock(
            elts=[
              Rupy.DAssign(
                reg="_._7",
                val=Rupy.DCall(
                  f=Rupy.DVar(
                    sym="main._4",
                  ),
                  args=[
                    Rupy.DConst(v=None),
                  ],
                ),
              ),
              Rupy.DConst(v=None),
            ],
          ),
        ),
      ],
    ),
    Rupy.DLoc(
      lineno=1,
      colno=1,
      val=Rupy.DConst(v=None),
    ),
  ],
)
filename = "/home/redbq/github/pythondev/rupy/a.pml"
compile_to(dexp, filename, "/home/redbq/github/pythondev/rupy/a.pyc")
